/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CheckinStatus = { 'pending' : null } |
  { 'struggling' : null } |
  { 'completed' : null } |
  { 'onTrack' : null };
export interface DashboardSummary {
  'completedGoalsCount' : bigint,
  'pendingCheckinsCount' : bigint,
  'upcomingCheckins' : Array<UpcomingCheckin>,
  'activeGoalsCount' : bigint,
}
export type GoalCategory = { 'work' : null } |
  { 'personal' : null };
export type GoalStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'archived' : null };
export interface Guidance {
  'encouragement' : string,
  'actionSteps' : Array<string>,
  'reframe' : string,
}
export interface UpcomingCheckin {
  'status' : CheckinStatus,
  'scheduledDate' : string,
  'goalTitle' : string,
  'checkinId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckin' : ActorMethod<[string, string, string], string>,
  'createGoal' : ActorMethod<[string, GoalCategory, string, string], string>,
  'deleteGoal' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logHurdle' : ActorMethod<[string, string], Guidance>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCheckinStatus' : ActorMethod<
    [string, CheckinStatus, string],
    undefined
  >,
  'updateGoal' : ActorMethod<
    [string, string, GoalCategory, string, string],
    undefined
  >,
  'updateGoalStatus' : ActorMethod<[string, GoalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];