/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GoalCategory = IDL.Variant({
  'work' : IDL.Null,
  'personal' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CheckinStatus = IDL.Variant({
  'pending' : IDL.Null,
  'struggling' : IDL.Null,
  'completed' : IDL.Null,
  'onTrack' : IDL.Null,
});
export const UpcomingCheckin = IDL.Record({
  'status' : CheckinStatus,
  'scheduledDate' : IDL.Text,
  'goalTitle' : IDL.Text,
  'checkinId' : IDL.Text,
});
export const DashboardSummary = IDL.Record({
  'completedGoalsCount' : IDL.Nat,
  'pendingCheckinsCount' : IDL.Nat,
  'upcomingCheckins' : IDL.Vec(UpcomingCheckin),
  'activeGoalsCount' : IDL.Nat,
});
export const Guidance = IDL.Record({
  'encouragement' : IDL.Text,
  'actionSteps' : IDL.Vec(IDL.Text),
  'reframe' : IDL.Text,
});
export const GoalStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'archived' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createGoal' : IDL.Func(
      [IDL.Text, GoalCategory, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteGoal' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logHurdle' : IDL.Func([IDL.Text, IDL.Text], [Guidance], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCheckinStatus' : IDL.Func([IDL.Text, CheckinStatus, IDL.Text], [], []),
  'updateGoal' : IDL.Func(
      [IDL.Text, IDL.Text, GoalCategory, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateGoalStatus' : IDL.Func([IDL.Text, GoalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GoalCategory = IDL.Variant({
    'work' : IDL.Null,
    'personal' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CheckinStatus = IDL.Variant({
    'pending' : IDL.Null,
    'struggling' : IDL.Null,
    'completed' : IDL.Null,
    'onTrack' : IDL.Null,
  });
  const UpcomingCheckin = IDL.Record({
    'status' : CheckinStatus,
    'scheduledDate' : IDL.Text,
    'goalTitle' : IDL.Text,
    'checkinId' : IDL.Text,
  });
  const DashboardSummary = IDL.Record({
    'completedGoalsCount' : IDL.Nat,
    'pendingCheckinsCount' : IDL.Nat,
    'upcomingCheckins' : IDL.Vec(UpcomingCheckin),
    'activeGoalsCount' : IDL.Nat,
  });
  const Guidance = IDL.Record({
    'encouragement' : IDL.Text,
    'actionSteps' : IDL.Vec(IDL.Text),
    'reframe' : IDL.Text,
  });
  const GoalStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'archived' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckin' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createGoal' : IDL.Func(
        [IDL.Text, GoalCategory, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteGoal' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logHurdle' : IDL.Func([IDL.Text, IDL.Text], [Guidance], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCheckinStatus' : IDL.Func(
        [IDL.Text, CheckinStatus, IDL.Text],
        [],
        [],
      ),
    'updateGoal' : IDL.Func(
        [IDL.Text, IDL.Text, GoalCategory, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateGoalStatus' : IDL.Func([IDL.Text, GoalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };